sudo: required
dist: bionic
language: node_js
node_js:
  - "14"
before_install:
  - sudo ntpdate 0.amazon.pool.ntp.org
  - sudo timedatectl set-timezone 'Europe/London'
  - date
install:
  - npm i
  - openssl version
  - npm run decrypt-data-ci
  - eval "$(ssh-agent -s)"
  - chmod 600 secrets/kp.pem
  - ssh-add secrets/kp.pem
  - ssh-add -l
  - npm run link
  - npm test
script: echo "npm test temporarily disabled"
