sudo: required
dist: bionic
language: node_js
node_js:
  - "14"

before_install:
  - sudo ntpdate 0.amazon.pool.ntp.org
  - sudo timedatectl set-timezone 'Europe/London'
  - date

install:
  - date
  - npm i
  - npm run link
  - DEBUG_CONSOLE=yes npm run test:mock
  - DEBUG_CONSOLE=yes npm run test:az
