version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  build-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run: sudo npm run link
      - run: npm test
workflows:
  node-tests:
    jobs:
      - build-test
