jobs:
  install-node:
    docker:
      - image: "cimg/base:stable"
      - tag: "latest"
    steps:
      - checkout
      - node/install:
      - run: node --version
      - run: sudo npm run link
      - run: npm test
orbs:
  node: circleci/node:14.9.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - install-node
