jobs:
  test:
    docker:
      - image: "cimg/node"
      - tag: "14.9.0"
    steps:
      - checkout
      - node/install:
      - run: node --version
      - run: sudo npm run link
      - run: npm test
orbs:
  node: circleci/node:4.0.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test
